### ISSUE TITLE
Docs:  "Java Client": Feedback for network YAML snippet

### ISSUE THREAD

**Issue by seii** [hazelcast/imdg-docs#191]
On the [Java Client](https://github.com/hazelcast/imdg-docs/blob/v4.2/docs/modules/clients/pages/java.adoc) page, the current YAML entry for the [Client Network](https://docs.hazelcast.com/imdg/4.2/clients/java.html#client-network) section is missing the `hazelcast-client` key.

Instead, it should look like this:
```
hazelcast-client:
  network:
    cluster-members:
      - 127.0.0.1
      - 127.0.0.2
    outbound-ports:
      - 34600
      - 34700-34710
    smart-routing: true
    redo-operation: true
    connection-timeout: 60000
    socket-options:
      ...
    socket-interceptor:
      ...
    ssl:
      enabled: false
      ...
    aws:
      enabled: true
      connection-timeout-seconds: 11
      ...
    gcp:
      enabled: false
      ...
    azure:
      enabled: false
      ...
    kubernetes:
      enabled: false
      ...
    eureka:
      enabled: false
      ...
    icmp-ping:
      enabled: false
      ...
    hazelcast-cloud:
      enabled: false
      discovery-token: EXAMPLE_TOKEN
    discovery-strategies:
      node-filter:
        class: DummyFilterClass
      discovery-strategies:
        - class: DummyDiscoveryStrategy1
          enabled: true
          properties:
            key-string: foo
            key-int: 123
            key-boolean: true
```
