### ISSUE TITLE
Docs: Feedback for Distributed Object Events

### ISSUE THREAD

**Issue by kitehunter** [hazelcast/imdg-docs#220]
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/master/docs/modules/events/pages/object-events.adoc)

For the entry listener config it should be 

```
hazelcast:
  map:
    somemap:
      entry-listeners:
        - class-name: com.your-package.MyEntryListener
          include-value: false
          local: false
```

iso

```
hazelcast:
  somemap:
    map:
      entry-listeners:
        - class-name: com.your-package.MyEntryListener
          include-value: false
          local: false
```
